#!/usr/bin/env php
<?php

require './vendor/autoload.php';

if ( ! isset($argv[1]))
    exit('Specify the source language'.PHP_EOL);

if ( ! isset($argv[2]))
    exit('Specify the translation to practice'.PHP_EOL);

$maxIterations = (isset($argv[3]))
    ? $argv[3]
    : null;

$words = new LTE\Words('words.csv');

$challenge = new LTE\Challenge($words->asAssocArray());
$challenge->setFromToLanguage($argv[1], $argv[2]);

$prompt = new \LTE\Prompt($challenge, $maxIterations);
$prompt->start();
$prompt->showSummary();
